// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://eqgrgrciyezkclcqmztu.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImVxZ3JncmNpeWV6a2NsY3FtenR1Iiwicm9sZSI6ImFub24iLCJpYXQiOjE3NzI2MTQzODMsImV4cCI6MjA4ODE5MDM4M30.BoEdjH3IbaLZMPEo9-pZqCoVMksCH99MoZ8ClPxdcCg";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});